-- @Author        : Rock Wayne
-- @Created       : 2020-08-03 21:30:23
-- @Last Modified : 2020-08-03 21:30:23
--
-- #Table: Users
-- #
-- #
-- #+----------------+---------+
-- #| Column Name    | Type    |
-- #+----------------+---------+
-- #| user_id        | int     |
-- #| join_date      | date    |
-- #| favorite_brand | varchar |
-- #+----------------+---------+
-- #此表主键是 user_id，表中描述了购物网站的用户信息，用户可以在此网站上进行商品买卖。
-- #
-- #
-- # Table: Orders
-- #
-- #
-- #+---------------+---------+
-- #| Column Name   | Type    |
-- #+---------------+---------+
-- #| order_id      | int     |
-- #| order_date    | date    |
-- #| item_id       | int     |
-- #| buyer_id      | int     |
-- #| seller_id     | int     |
-- #+---------------+---------+
-- #此表主键是 order_id，外键是 item_id 和（buyer_id，seller_id）。
-- #
-- #
-- # Table: Item
-- #
-- #
-- #+---------------+---------+
-- #| Column Name   | Type    |
-- #+---------------+---------+
-- #| item_id       | int     |
-- #| item_brand    | varchar |
-- #+---------------+---------+
-- #此表主键是 item_id。
-- #
-- #
-- #
-- #
-- # 请写出一条SQL语句以查询每个用户的注册日期和在 2019 年作为买家的订单总数。
-- #
-- # 查询结果格式如下：
-- #
-- #
-- #Users table:
-- #+---------+------------+----------------+
-- #| user_id | join_date  | favorite_brand |
-- #+---------+------------+----------------+
-- #| 1       | 2018-01-01 | Lenovo         |
-- #| 2       | 2018-02-09 | Samsung        |
-- #| 3       | 2018-01-19 | LG             |
-- #| 4       | 2018-05-21 | HP             |
-- #+---------+------------+----------------+
-- #
-- #Orders table:
-- #+----------+------------+---------+----------+-----------+
-- #| order_id | order_date | item_id | buyer_id | seller_id |
-- #+----------+------------+---------+----------+-----------+
-- #| 1        | 2019-08-01 | 4       | 1        | 2         |
-- #| 2        | 2018-08-02 | 2       | 1        | 3         |
-- #| 3        | 2019-08-03 | 3       | 2        | 3         |
-- #| 4        | 2018-08-04 | 1       | 4        | 2         |
-- #| 5        | 2018-08-04 | 1       | 3        | 4         |
-- #| 6        | 2019-08-05 | 2       | 2        | 4         |
-- #+----------+------------+---------+----------+-----------+
-- #
-- #Items table:
-- #+---------+------------+
-- #| item_id | item_brand |
-- #+---------+------------+
-- #| 1       | Samsung    |
-- #| 2       | Lenovo     |
-- #| 3       | LG         |
-- #| 4       | HP         |
-- #+---------+------------+
-- #
-- #Result table:
-- #+-----------+------------+----------------+
-- #| buyer_id  | join_date  | orders_in_2019 |
-- #+-----------+------------+----------------+
-- #| 1         | 2018-01-01 | 1              |
-- #| 2         | 2018-02-09 | 2              |
-- #| 3         | 2018-01-19 | 0              |
-- #| 4         | 2018-05-21 | 0              |
-- #+-----------+------------+----------------+
-- #
-- # 👍 9 👎 0
--
--
--
-- #leetcode submit region begin(Prohibit modification and deletion)
-- # Write your MySQL query statement below


select u.user_id as buyer_id, u.join_date, ifnull(os.cnt, 0) as orders_in_2019
from Users as u
         left join (
    select buyer_id, count(order_id) as cnt from Orders where EXTRACT(year from order_date) = 2019 group by buyer_id
) as os on u.user_id = os.buyer_id;

-- WHERE  Year(order_date) = 2019

-- #leetcode submit region end(Prohibit modification and deletion)
	